### ISSUE TITLE
Inputting the helpers.... Newbie

### ISSUE THREAD

**Issue by Yakuzama8391** [DJS91/HAMusicAssistantJukebox#14]
I'm trying to follow along with the instructions to install the jukebox overlay but I am currently stuck on where/how to input the helpers as shown below:

input_boolean:
  songrequestaccess:
    name: Song Request Access
    initial: off
  jukebox_queue:
    name: Jukebox Queue Mode
    initial: off
input_number:
  jukebox_queue_length:
    name: Jukebox Queue Length
    initial: 0

Can someone please advise in specific layman terms the procedure required to input theses helpers?

I thank-you in advance.

**Comment by jonwaland** [comment]
I created a package and put as much as I could in there:

```
#################################################################
#                                                               #
#                     Packages/jukebox                          #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                            Inputs                             #
#                                                               #
#################################################################

input_boolean:
  songrequestaccess:
    name: Song Request Access
    initial: off

  jukebox_queue:
    name: Jukebox Queue Mode
    initial: off


input_number:
  jukebox_queue_length:
    name: Jukebox Queue Length
    initial: 0
    min: 0
    max: 10000



#################################################################
#                                                               #
#                      Automations                              #
#                                                               #
#################################################################


automation:

##
##
  - alias: Jukebox - Notify of Queued Song
    description: "Tells home assistant that someone has requested a song and to switch the queueing mode for guests for further requests"
    triggers:
      - trigger: webhook
        allowed_methods:
          - POST
          - GET
        local_only: false
        webhook_id: Juke_Box
    conditions: []
    actions:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.jukebox_queue

##
##
  - alias: Jukebox - Set Default Playlist when Jukebox Queue is zero
    description: "Once the guests queued songs are all played, play the default party playlist so the music doesnt stop"
    triggers:
      - trigger: state
        entity_id:
          - input_number.jukebox_queue_length
        to: "0.0"
    conditions: []
    actions:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.jukebox_queue
      - action: music_assistant.play_media
        metadata: {}
        data:
          enqueue: play
          media_id: "Friday Pop Remix"
          media_type: playlist
        target:
          entity_id: media_player.study_speaker_2
    mode: single

##
##
  - alias: Jukebox - Track Queue Size
    description: "Keeps track of the media player queue length and updates the Jukebox Queue Length helper"
    triggers:
      - trigger: state
        entity_id:
          - media_player.group_ground_floor
        attribute: media_position_updated_at
    conditions: []
    actions:
      - action: music_assistant.get_queue
        metadata: {}
        data: {}
        target:
          entity_id: media_player.study_speaker_2
        response_variable: jukeboxqueuedetail
      - variables:
          speaker_data: "{{ jukeboxqueuedetail['media_player.study_speaker_2'] }}"
      - variables:
          items_count: >-
            {% set matches = speaker_data | regex_findall("'items': (\d+)") %} {{
            matches[0] if matches else 0 }}
      - action: input_number.set_value
        target:
          entity_id: input_number.jukebox_queue_length
        data:
          value: "{{ items_count | float }}"
    mode: queued
    max: 10


  - alias: Jukebox - Switch Jukebox Access on/off
    description: "Controls access to the jukebox by enableing the app and provisioning an access token or disabling the app and revoking any active token"
    triggers:
      - trigger: state
        entity_id:
          - input_boolean.songrequestaccess
        from: "off"
        to: "on"
      - trigger: state
        entity_id:
          - input_boolean.songrequestaccess
        from: "on"
        to: "off"
    conditions: []
    actions:
      - if:
          - condition: state
            entity_id: input_boolean.songrequestaccess
            state: "on"
        then:
          - action: shell_command.create_jukebox_token
            metadata: {}
            data: {}
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.jukebox_queue
        else:
          - action: shell_command.delete_jukebox_token
            metadata: {}
            data: {}
    mode: single

#################################################################
#                                                               #
#                      shell_command                            #
#                                                               #
#################################################################

shell_command:
   create_jukebox_token: python3 ./python_scripts/manage_token.py
   delete_jukebox_token: python3 ./python_scripts/manage_token.py delete //revokes they key and deletes the key file from config/www


```

Obviously you need to change the media player and playlist to fit your config
