### ISSUE TITLE
False output from "Jukebox - Set Default Playlist when Jukebox Queue is Zero.yaml" automation

### ISSUE THREAD

**Issue by NeurosProjekte** [DJS91/HAMusicAssistantJukebox#9]
So I worked further with the system and found some problems in the automations.

The output of the queue reader always shows the number of the complete playlist, even if the songs are already played. It looks like it was the sum value of played songs + the songs that are still in the queue.

With that, the actual automation in the default setup does not restart the default playlist if there is no song left.
I reworked two automations to work around that problem, maybe you want to implement that.

At first the queue size:
```
alias: Automation - Musiksystem - Party Track Queue Size
description: >-
  Keeps track of the media player queue length and updates the Jukebox Queue
  Length helper
triggers:
  - trigger: state
    entity_id:
      - media_player.your_media_player
    attribute: media_position_updated_at
conditions: []
actions:
  - action: music_assistant.get_queue
    metadata: {}
    data: {}
    target:
      entity_id: media_player.snapclient_terrasse2
    response_variable: jukeboxqueuedetail
  - variables:
      speaker_data: "{{ jukeboxqueuedetail['media_player.your_media_player'] }}"
  - variables:
      items_count: >-
        {% set matches = speaker_data | regex_findall("'items': (\d+)") %} {{
        matches[0] if matches else 0 }}
  - variables:
      items_played: >-
        {% set matches = speaker_data | regex_findall("'current_index': (\d+)")
        %} {{ matches[0] if matches else 0 }}
  - action: input_number.set_value
    target:
      entity_id: input_number.jukebox_queue_length
    data:
      value: "{{ items_count | float - items_played | float }}"
mode: queued
max: 10
```

With that change in the code, it looks into the current index and substract the number of the current played song in the playlist from the complete playlist number of songs. This works as long as there is one song left, so there never is a 0 written to the jukebox_queue_length.

With that in mind and another problem I had, I then changed the automation for setting the default playlist a bit:
```
alias: Automation - Musiksystem - Set Default Playlist when Jukebox Queue is zero
description: >-
  Once the guests queued songs are all played, play the default party playlist
  so the music doesnt stop
triggers:
  - trigger: state
    entity_id:
      - input_boolean.songrequestaccess
    to: "on"
    from: "off"
  - trigger: state
    entity_id:
      - media_player.your_media_player
    attribute: media_position
    for:
      hours: 0
      minutes: 0
      seconds: 0
conditions:
  - condition: state
    entity_id: input_boolean.songrequestaccess
    state: "on"
  - condition: numeric_state
    entity_id: input_number.jukebox_queue_length
    below: 2
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - if:
      - condition: device
        device_id: <your media player device id>
        domain: media_player
        entity_id: <your media player entity id>
        type: is_idle
    then:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.jukebox_queue
      - action: music_assistant.play_media
        metadata: {}
        data:
          enqueue: play
          media_id: <playlist name>
          media_type: playlist
        target:
          entity_id: media_player.your_media_player
mode: single
```

Best variant is to edit this in the visual editor after paste the code in the yaml editor.

What this does:
- Start the default playlist after switching on the access to the party system when the playlist is empty already
- Checks after media player has stopped if the remaining number of songs in the playlist is below 2, if so it activates the default playlist
- Toggles the helper of the jukebox_queue to off (as already in the code)
- Also restarts the default playlist after it is played completly

Hope that helps a bit to further develop this and making it easier for others to implement in their setups :-)
